### ISSUE TITLE
@Klownes1

### ISSUE THREAD

**Issue by RedQueen-dev** [serge3ling/test-react-weird-calc#2]
@Klownes1

_Originally posted by @RedQueen-dev in https://github.com/serge3ling/test-react-weird-calc/issues/1#issuecomment-693271193_

**Comment by RedQueen-dev** [comment]
> if Code worked then Hacked true

> `Best security ever'

**Comment by kryptonitechic** [comment]
@RedQueen-dev ,Samsung would also love your services.
